# Generated by Django 5.1.7 on 2025-08-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250824_1739'),
    ]

    operations = [
    ]
