name: "DXB Frontend"
description: "React frontend для платформы недвижимости Dubai"
type: "frontend"
category: "real-estate"
priority: "high"

# Docker Compose конфигурация
compose:
  file: "../../../DXB-frontend-develop/docker-compose.yml"
  profile: "development"
  working_dir: "../../../DXB-frontend-develop"

# Настройки окружения
environment: "development"
auto_start: true
auto_restart: true
restart_policy: "unless-stopped"

# Health Check
health_check:
  url: "http://localhost:3000/health"
  interval: 30
  timeout: 10
  retries: 3
  method: "GET"
  expected_status: 200

# Ресурсы
resources:
  cpu_limit: "1.0"
  memory_limit: "2GB"
  disk_limit: "10GB"
  network_mode: "bridge"

# Порты
ports:
  - "3000:3000"
  - "3001:3001"  # Для дополнительных сервисов

# Переменные окружения
environment_variables:
  NODE_ENV: "development"
  REACT_APP_API_URL: "http://localhost:8000"
  REACT_APP_MEMORY_LLM_URL: "http://localhost:8081"
  CHOKIDAR_USEPOLLING: "true"
  PORT: "3000"

# Зависимости
dependencies:
  - "memory-llm"
  - "realty-backend"
  - "pfimport-service"

# Мониторинг
monitoring:
  enabled: true
  metrics:
    - "cpu"
    - "memory"
    - "network"
    - "disk"
    - "response_time"
    - "error_rate"
  
  # Алерты
  alerts:
    - name: "High CPU Usage"
      condition: "cpu > 80%"
      action: "restart"
      cooldown: 300
      severity: "warning"
    
    - name: "High Memory Usage"
      condition: "memory > 85%"
      action: "restart"
      cooldown: 300
      severity: "warning"
    
    - name: "Service Unavailable"
      condition: "health_check_failed > 3"
      action: "restart"
      cooldown: 60
      severity: "critical"

# Логирование
logging:
  level: "info"
  format: "json"
  retention: "30d"
  max_size: "100MB"
  
  # Фильтры
  filters:
    - "error"
    - "warn"
    - "info"

# Backup
backup:
  enabled: true
  schedule: "0 2 * * *"  # Ежедневно в 2:00
  retention: "7d"
  include:
    - "src/"
    - "package.json"
    - "package-lock.json"
  exclude:
    - "node_modules/"
    - "build/"
    - ".git/"

# CI/CD
ci_cd:
  enabled: true
  auto_deploy: true
  branch: "main"
  triggers:
    - "push"
    - "pull_request"
  
  # Тестирование
  testing:
    unit_tests: true
    integration_tests: true
    e2e_tests: false
  
  # Сборка
  build:
    command: "npm run build"
    artifacts: ["build/"]
    cache: ["node_modules/"]

# Масштабирование
scaling:
  min_replicas: 1
  max_replicas: 3
  target_cpu_utilization: 70
  target_memory_utilization: 80
  
  # Автоскейлинг
  auto_scaling:
    enabled: true
    scale_up_threshold: 80
    scale_down_threshold: 30
    scale_up_cooldown: 300
    scale_down_cooldown: 300

# Безопасность
security:
  # Сканирование уязвимостей
  vulnerability_scanning:
    enabled: true
    schedule: "0 3 * * *"  # Ежедневно в 3:00
    tools: ["npm audit", "snyk"]
  
  # Секреты
  secrets:
    - "REACT_APP_API_KEY"
    - "REACT_APP_SECRET"
  
  # Сетевая безопасность
  network:
    allowed_ips: ["127.0.0.1", "::1"]
    firewall_rules:
      - port: 3000
        protocol: "tcp"
        source: "any"

# Документация
documentation:
  readme: "../../../DXB-frontend-develop/README.md"
  api_docs: "../../../DXB-frontend-develop/docs/api/"
  user_guide: "../../../DXB-frontend-develop/docs/user-guide/"
  
  # Ссылки
  links:
    - name: "GitHub Repository"
      url: "https://github.com/dubai-project/dxb-frontend"
    - name: "Live Demo"
      url: "http://localhost:3000"
    - name: "API Documentation"
      url: "http://localhost:3000/docs"

# Теги для поиска и фильтрации
tags:
  - "frontend"
  - "react"
  - "typescript"
  - "real-estate"
  - "dubai"
  - "ai-powered"
  - "responsive"

# Метаданные
metadata:
  created: "2025-01-16"
  updated: "2025-01-16"
  version: "1.0.0"
  maintainer: "dubai-team@company.com"
  status: "active"
