# Generated by Django 5.1.7 on 2025-08-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userreporthistory',
            new_name='api_userrep_user_id_bc717e_idx',
            old_name='api_userrepor_user_id_0a1234_idx',
        ),
        migrations.RenameIndex(
            model_name='userreporthistory',
            new_name='api_userrep_report__c9814c_idx',
            old_name='api_userrepor_report__5b2345_idx',
        ),
        migrations.RenameIndex(
            model_name='userreporthistory',
            new_name='api_userrep_generat_3c6c69_idx',
            old_name='api_userrepor_generat_6c3456_idx',
        ),
    ]
