# Generated by Django 5.1.7 on 2025-08-24 14:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250824_1739'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='property_analysis', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('parameters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'User Report History',
                'verbose_name_plural': 'User Report Histories',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Code', 'verbose_name_plural': 'OTP Codes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymenteventaudit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Event Audit', 'verbose_name_plural': 'Payment Event Audits'},
        ),
        migrations.RemoveConstraint(
            model_name='paymenteventaudit',
            name='uniq_provider_event',
        ),
        migrations.RemoveIndex(
            model_name='paymenteventaudit',
            name='idx_idem_key',
        ),
        migrations.RenameField(
            model_name='paymenteventaudit',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameIndex(
            model_name='paymenteventaudit',
            new_name='api_payment_provide_59f71e_idx',
            old_name='idx_provider_event',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_aed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='attempt_count',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='AED', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymenteventaudit',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='api.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='succeeded', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenteventaudit',
            name='event_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenteventaudit',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='paymenteventaudit',
            name='status',
            field=models.CharField(default='received', max_length=32),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['email'], name='api_otpcode_email_bee0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['created_at'], name='api_otpcode_created_572054_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='api_payment_user_id_03c2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_charge_id'], name='api_payment_stripe__0cead4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='api_payment_status_c61efc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenteventaudit',
            index=models.Index(fields=['event_type'], name='api_payment_event_t_1402b4_idx'),
        ),
        migrations.AlterModelTable(
            name='otpcode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymenteventaudit',
            table=None,
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='api_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userreporthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
        migrations.AddIndex(
            model_name='userreporthistory',
            index=models.Index(fields=['user'], name='api_userrep_user_id_bc717e_idx'),
        ),
        migrations.AddIndex(
            model_name='userreporthistory',
            index=models.Index(fields=['report_type'], name='api_userrep_report__c9814c_idx'),
        ),
        migrations.AddIndex(
            model_name='userreporthistory',
            index=models.Index(fields=['generated_at'], name='api_userrep_generat_3c6c69_idx'),
        ),
    ]
