# Generated by Django 5.2.5 on 2025-08-26 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_otpcode_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymenteventaudit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Event Audit', 'verbose_name_plural': 'Payment Event Audits'},
        ),
        migrations.RemoveConstraint(
            model_name='paymenteventaudit',
            name='uniq_provider_event',
        ),
        migrations.RemoveIndex(
            model_name='paymenteventaudit',
            name='idx_idem_key',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='paymenteventaudit',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='api_otpcode_email_bee0a2_idx',
            old_name='api_otpcode_email_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='api_otpcode_created_572054_idx',
            old_name='api_otpcode_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenteventaudit',
            new_name='api_payment_provide_59f71e_idx',
            old_name='idx_provider_event',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_aed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='attempt_count',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymenteventaudit',
            name='signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='AED', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymenteventaudit',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='api.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='succeeded', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenteventaudit',
            name='event_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenteventaudit',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='paymenteventaudit',
            name='status',
            field=models.CharField(default='received', max_length=32),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='api_payment_user_id_03c2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_charge_id'], name='api_payment_stripe__0cead4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='api_payment_status_c61efc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenteventaudit',
            index=models.Index(fields=['event_type'], name='api_payment_event_t_1402b4_idx'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymenteventaudit',
            table=None,
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
