// Моковые данные для таблиц отчетов
export const mockReportsTableData = [
  {
    key: '1',
    property: 'Burj Khalifa Tower',
    location: 'Downtown Dubai',
    type: 'apartment',
    price: 2800000,
    pricePerSqm: 18500,
    area: 151,
    bedrooms: '2 BR',
    status: 'active' as const,
    roi: 8.2,
    lastUpdate: '2024-01-20',
  },
  {
    key: '2',
    property: 'Marina Heights',
    location: 'Dubai Marina',
    type: 'apartment',
    price: 1950000,
    pricePerSqm: 16250,
    area: 120,
    bedrooms: '1 BR',
    status: 'pending' as const,
    roi: 7.1,
    lastUpdate: '2024-01-19',
  },
  {
    key: '3',
    property: 'Palm Villa Residence',
    location: 'Palm Jumeirah',
    type: 'villa',
    price: 8500000,
    pricePerSqm: 21250,
    area: 400,
    bedrooms: '4 BR',
    status: 'active' as const,
    roi: 6.8,
    lastUpdate: '2024-01-18',
  },
  {
    key: '4',
    property: 'JBR Beach Apartments',
    location: 'JBR',
    type: 'apartment',
    price: 3200000,
    pricePerSqm: 20000,
    area: 160,
    bedrooms: '3 BR',
    status: 'sold' as const,
    roi: 9.1,
    lastUpdate: '2024-01-17',
  },
  {
    key: '5',
    property: 'Business Bay Tower',
    location: 'Business Bay',
    type: 'office',
    price: 1200000,
    pricePerSqm: 15000,
    area: 80,
    bedrooms: 'Office',
    status: 'active' as const,
    roi: 5.2,
    lastUpdate: '2024-01-16',
  },
  {
    key: '6',
    property: 'DIFC Gate Building',
    location: 'DIFC',
    type: 'office',
    price: 2100000,
    pricePerSqm: 17500,
    area: 120,
    bedrooms: 'Office',
    status: 'pending' as const,
    roi: 6.4,
    lastUpdate: '2024-01-15',
  },
  {
    key: '7',
    property: 'Jumeirah Townhouse',
    location: 'Jumeirah',
    type: 'townhouse',
    price: 4500000,
    pricePerSqm: 18750,
    area: 240,
    bedrooms: '3 BR',
    status: 'active' as const,
    roi: 7.9,
    lastUpdate: '2024-01-14',
  },
  {
    key: '8',
    property: 'Deira Heritage Apartments',
    location: 'Deira',
    type: 'apartment',
    price: 890000,
    pricePerSqm: 11125,
    area: 80,
    bedrooms: '1 BR',
    status: 'active' as const,
    roi: 8.8,
    lastUpdate: '2024-01-13',
  },
  {
    key: '9',
    property: 'Emirates Hills Villa',
    location: 'Emirates Hills',
    type: 'villa',
    price: 12500000,
    pricePerSqm: 25000,
    area: 500,
    bedrooms: '5 BR',
    status: 'pending' as const,
    roi: 5.8,
    lastUpdate: '2024-01-12',
  },
  {
    key: '10',
    property: 'The Views Apartment',
    location: 'Emirates Golf Club',
    type: 'apartment',
    price: 1650000,
    pricePerSqm: 15000,
    area: 110,
    bedrooms: '2 BR',
    status: 'sold' as const,
    roi: 7.6,
    lastUpdate: '2024-01-11',
  },
  {
    key: '11',
    property: 'Al Barsha Heights',
    location: 'Al Barsha',
    type: 'apartment',
    price: 1250000,
    pricePerSqm: 13889,
    area: 90,
    bedrooms: '1 BR',
    status: 'active' as const,
    roi: 8.1,
    lastUpdate: '2024-01-10',
  },
  {
    key: '12',
    property: 'Motor City Townhouse',
    location: 'Motor City',
    type: 'townhouse',
    price: 2800000,
    pricePerSqm: 14000,
    area: 200,
    bedrooms: '3 BR',
    status: 'active' as const,
    roi: 9.2,
    lastUpdate: '2024-01-09',
  },
];

export const generateReportsData = (count: number = 25) => {
  const locations = [
    'Downtown Dubai', 'Dubai Marina', 'JBR', 'Palm Jumeirah', 'Business Bay',
    'DIFC', 'Jumeirah', 'Deira', 'Emirates Hills', 'Al Barsha', 'Motor City',
    'Dubai Hills', 'Arabian Ranches', 'The Springs', 'Discovery Gardens'
  ];
  
  const propertyTypes = ['apartment', 'villa', 'townhouse', 'office'];
  const bedrooms = ['Studio', '1 BR', '2 BR', '3 BR', '4 BR', '5 BR', 'Office'];
  const statuses = ['active', 'pending', 'sold'] as const;
  
  return Array.from({ length: count }, (_, i) => ({
    key: (i + 1).toString(),
    property: `Property ${i + 1}`,
    location: locations[Math.floor(Math.random() * locations.length)],
    type: propertyTypes[Math.floor(Math.random() * propertyTypes.length)],
    price: Math.floor(Math.random() * 10000000) + 500000,
    pricePerSqm: Math.floor(Math.random() * 15000) + 10000,
    area: Math.floor(Math.random() * 400) + 50,
    bedrooms: bedrooms[Math.floor(Math.random() * bedrooms.length)],
    status: statuses[Math.floor(Math.random() * statuses.length)],
    roi: Math.round((Math.random() * 10 + 3) * 10) / 10,
    lastUpdate: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  }));
};
