version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/DXB-frontend-develop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/apps/realty-main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
