# содержит количество объявлений для каждого района
AREAS_WITH_PROPERTY = {
    "Jumeirah Village Circle": 7431,
    "Business Bay": 5416,
    "Downtown Dubai": 5200,
    "Dubai Marina": 4558,
    "Mohammed Bin Rashid City": 1855,
    "Palm Jumeirah": 1758,
    "Arjan": 1757,
    "Dubai Creek Harbour (The Lagoons)": 1731,
    "Al Furjan": 1640,
    "Jumeirah Lake Towers": 1522,
    "Jumeirah Beach Residence": 1455,
    "Al Jaddaf": 1441,
    "Meydan": 1407,
    "Sheikh Zayed Road": 1347,
    "Al Satwa": 1278,
    "Al Barsha": 1000,
    "Dubai Hills Estate": 992,
    "Dubai Harbour": 916,
    "Bur Dubai": 760,
    "Town Square": 648,
    "Dubai Silicon Oasis": 640,
    "Dubai Sports City": 627,
    "Al Warsan": 565,
    "Dubai Land": 539,
    "Zabeel": 508,
    "Dubai South (Dubai World Central)": 458,
    "DAMAC Hills": 454,
    "Al Nahda": 426,
    "Jumeirah": 412,
    "The Gardens": 377,
    "Barsha Heights (Tecom)": 357,
    "Deira": 345,
    "Dubai Production City (IMPZ)": 340,
    "DIFC": 328,
    "Greens": 327,
    "The Views": 278,
    "Al Wasl": 274,
    "Bluewaters": 250,
    "Umm Suqeim": 233,
    "City Walk": 228,
    "Expo City": 220,
    "Jumeirah Village Triangle": 216,
    "Downtown Jebel Ali": 198,
    "Discovery Gardens": 194,
    "Old Town": 164,
    "Al Sufouh": 160,
    "International City": 153,
    "Culture Village": 148,
    "Al Warqa'a": 144,
    "Dubai Land Residence Complex": 121,
    "Motor City": 109,
    "Dubai Festival City": 104,
    "Al Muhaisnah": 103,
    "Dubai Studio City": 85,
    "Wasl Gate": 85,
    "Damac Hills 2": 78,
    "Dubai Investment Park (DIP)": 71,
    "Al Qusais": 70,
    "Al Barari": 69,
    "The Hills": 67,
    "World Trade Center": 61,
    "Mirdif": 55,
    "Jumeirah Golf Estates": 47,
    "Maritime City": 45,
    "Dubai Media City": 42,
    "Al Garhoud": 34,
    "Dubai Science Park": 32,
    "Al Karama": 30,
    "Al Quoz": 28,
    "Jebel Ali": 28,
    "Al Mina": 23,
    "Umm Hurair": 21,
    "Academic City": 16,
    "Nadd Al Hammar": 14,
    "Wadi Al Safa 2": 10,
    "Jumeirah Islands": 9,
    "Nad Al Sheba": 8,
    "Living Legends": 8,
    "Mudon": 7,
    "Dubai Outsource Zone": 6,
    "DuBiotech": 6,
    "Wadi Al Safa 3": 5,
    "Dubai Waterfront": 5,
    "Umm Ramool": 4,
    "Tilal Al Ghaf": 4,
    "Al Badaa": 4,
    "Al Safa": 4,
    "Dubai Industrial City": 4,
    "Al Shindagah": 3,
    "Al Aweer": 2,
    "Al Yelayiss 2": 2,
    "The Villa": 2,
    "The Springs": 2,
    "Arabian Ranches": 2,
    "The Lakes": 1,
    "Al Mizhar": 1,
    "Umm Al Sheif": 1,
    "Wadi Al Safa 5": 1,
    "Jumeirah Park": 1,
    "Al Khawaneej": 1,
    "The Valley": 1,
    "Mohammad Bin Rashid Gardens": 1,
    "Arabian Ranches 3": 1,
}
