version: '3.8'

services:
  # ========================================
  # Database
  # ========================================
  postgres:
    image: postgres:16-alpine
    container_name: dubai-postgres-local
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dubai_realty_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # ========================================
  # Redis (для кеширования и сессий)
  # ========================================
  redis:
    image: redis:7-alpine
    container_name: dubai-redis-local
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # ========================================
  # Django Backend
  # ========================================
  django:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: dubai-django-local
    volumes:
      - .:/app
      - /app/static
      - /app/media
      - /app/logs
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] 0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dubai_realty_local
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=realty.settings
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000"

  # ========================================
  # Frontend (React)
  # ========================================
  frontend:
    build:
      context: ./apps/DXB-frontend-develop
      dockerfile: Dockerfile
    container_name: dubai-frontend-local
    ports:
      - "3000:80"
    volumes:
      - ./apps/DXB-frontend-develop:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - django
    restart: unless-stopped

  # ========================================
  # Direct Access (nginx removed)
  # Frontend: http://localhost:3000
  # Backend: http://localhost:8000
  # ========================================

volumes:
  postgres_data:
  redis_data:
