version: "3.8"

# Загружаем переменные окружения
env_file:
  - .env.production
  - global-ports.env

services:
  # --- Monitoring ---
  prometheus:
    image: prom/prometheus:latest
    container_name: memory-prometheus
    volumes:
      - ./configs/monitoring/prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    ports:
      - "${MEMORY_PROMETHEUS_PORT:-9090}:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana для дашбордов
  grafana:
    image: grafana/grafana:latest
    container_name: memory-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./configs/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - "${MEMORY_GRAFANA_PORT:-3003}:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  nginx_logs:
  prometheus_data:
  grafana_data:
