# Generated by Django 5.1.7 on 2025-05-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building_reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildingreportsnapshot",
            old_name="rooms_count_sales",
            new_name="rooms_count",
        ),
        migrations.RenameField(
            model_name="buildingreportsnapshot",
            old_name="rooms_count_sales_prev",
            new_name="rooms_count_prev",
        ),
    ]
