# Generated by Django 5.1.7 on 2025-05-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "building_reports",
            "0002_rename_rooms_count_sales_buildingreportsnapshot_rooms_count_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildingreportsnapshot",
            old_name="rooms_count",
            new_name="rooms_count_sales",
        ),
        migrations.RenameField(
            model_name="buildingreportsnapshot",
            old_name="rooms_count_prev",
            new_name="rooms_count_sales_prev",
        ),
    ]
