# Generated by Django 5.1.7 on 2025-05-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0020_masterproject_building_area_by_pf_and_more"),
        (
            "pfimport",
            "0007_area_created_by_area_geometry_json_building_latitude_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_ppsqm_rent_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_sqm_by_building_py", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_by_building_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_ppsqm_rent_by_building_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_roi_py", models.FloatField(blank=True, null=True)),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1br", "1 B/R"),
                            ("2br", "2 B/R"),
                            ("3br", "3 B/R"),
                            ("4br", "4 B/R"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "avg_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "avg_price_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("avg_exposure_days", models.FloatField(blank=True, null=True)),
                (
                    "avg_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "avg_rent_price_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("avg_exposure_rent_days", models.FloatField(blank=True, null=True)),
                ("avg_rent_per_unit_ratio", models.FloatField(blank=True, null=True)),
                ("avg_roi", models.FloatField(blank=True, null=True)),
                ("avg_sale_per_unit_ratio", models.FloatField(blank=True, null=True)),
                (
                    "avg_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_sale_ly", models.PositiveIntegerField(blank=True, null=True)),
                ("count_sale_py", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_rent_ly", models.PositiveIntegerField(blank=True, null=True)),
                ("count_rent_py", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_rent_per_unit_ratio_ly",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_rent_per_unit_ratio_py",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_sale_per_unit_ratio_ly",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_sale_per_unit_ratio_py",
                    models.FloatField(blank=True, null=True),
                ),
                ("avg_sqm_by_building", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт по городуDLD",
                "verbose_name_plural": "Отчёты по городуDLD",
            },
        ),
        migrations.CreateModel(
            name="CityReportPF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1br", "1 B/R"),
                            ("2br", "2 B/R"),
                            ("3br", "3 B/R"),
                            ("4br", "4 B/R"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "avg_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "avg_price_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("avg_exposure_days", models.FloatField(blank=True, null=True)),
                (
                    "avg_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "avg_rent_price_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("avg_exposure_rent_days", models.FloatField(blank=True, null=True)),
                ("avg_rent_per_unit_ratio", models.FloatField(blank=True, null=True)),
                ("avg_roi", models.FloatField(blank=True, null=True)),
                ("avg_sale_per_unit_ratio", models.FloatField(blank=True, null=True)),
                (
                    "avg_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_sale_ly", models.PositiveIntegerField(blank=True, null=True)),
                ("count_sale_py", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_rent_ly", models.PositiveIntegerField(blank=True, null=True)),
                ("count_rent_py", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_rent_per_unit_ratio_ly",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_rent_per_unit_ratio_py",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_sale_per_unit_ratio_ly",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_sale_per_unit_ratio_py",
                    models.FloatField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Отчёт по городу",
                "verbose_name_plural": "Отчёты по городу",
            },
        ),
        migrations.CreateModel(
            name="AreaReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1br", "1 B/R"),
                            ("2br", "2 B/R"),
                            ("3br", "3 B/R"),
                            ("4br", "4 B/R"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "avg_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "avg_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "avg_sale_price_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "avg_rent_price_by_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("avg_exposure_sale_days", models.FloatField(blank=True, null=True)),
                ("avg_exposure_rent_days", models.FloatField(blank=True, null=True)),
                ("avg_sale_per_unit_ratio", models.FloatField(blank=True, null=True)),
                ("avg_rent_per_unit_ratio", models.FloatField(blank=True, null=True)),
                ("avg_roi", models.FloatField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_reports",
                        to="pfimport.area",
                    ),
                ),
            ],
            options={
                "unique_together": {("area", "bedrooms")},
            },
        ),
        migrations.CreateModel(
            name="AreaReportDLD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1br", "1 B/R"),
                            ("2br", "2 B/R"),
                            ("3br", "3 B/R"),
                            ("4br", "4 B/R"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "avg_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_sqm_sale_ly", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_sale_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_sale_ly", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_sqm_rent_ly", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_rent_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_rent_ly", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_price_by_building_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_price_by_building_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_tx_per_building_ly", models.FloatField(blank=True, null=True)),
                ("avg_roi_by_building_ly", models.FloatField(blank=True, null=True)),
                ("last_3_sales", models.JSONField(blank=True, null=True)),
                ("last_3_rents", models.JSONField(blank=True, null=True)),
                (
                    "avg_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_sqm_sale_py", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_sale_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_sale_py", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_price_by_building_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_price_by_building_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_tx_per_building_py", models.FloatField(blank=True, null=True)),
                ("avg_roi_by_building_py", models.FloatField(blank=True, null=True)),
                (
                    "avg_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_sqm_rent_py", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_rent_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_rent_py", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_tx_per_building_ly_rent",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_tx_per_building_py_rent",
                    models.FloatField(blank=True, null=True),
                ),
                ("avg_exposure_sale_days", models.FloatField(blank=True, null=True)),
                ("avg_exposure_rent_days", models.FloatField(blank=True, null=True)),
                ("avg_sale_per_unit_ratio", models.FloatField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="main.area",
                    ),
                ),
            ],
            options={
                "unique_together": {("area", "bedrooms")},
            },
        ),
        migrations.CreateModel(
            name="BuildingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1br", "1 B/R"),
                            ("2br", "2 B/R"),
                            ("3br", "3 B/R"),
                            ("4br", "4 B/R"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "avg_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sale_count", models.PositiveIntegerField(default=0)),
                ("avg_exposure_sale_days", models.FloatField(blank=True, null=True)),
                ("sale_per_unit_ratio", models.FloatField(blank=True, null=True)),
                (
                    "avg_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rent_count", models.PositiveIntegerField(default=0)),
                ("avg_exposure_rent_days", models.FloatField(blank=True, null=True)),
                ("rent_per_unit_ratio", models.FloatField(blank=True, null=True)),
                ("type_of_rooms_in", models.JSONField(blank=True, null=True)),
                ("roi", models.FloatField(blank=True, null=True)),
                ("total_units", models.PositiveIntegerField(default=0)),
                ("units", models.PositiveIntegerField(default=0)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfimport.area",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="pfimport.building",
                    ),
                ),
                (
                    "dld_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.area",
                    ),
                ),
                (
                    "dld_building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.building",
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "bedrooms")},
            },
        ),
        migrations.CreateModel(
            name="DldBuildingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1br", "1 B/R"),
                            ("2br", "2 B/R"),
                            ("3br", "3 B/R"),
                            ("4br", "4 B/R"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "avg_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_sqm_sale_ly", models.FloatField(blank=True, null=True)),
                ("avg_sqm_rent_ly", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_sale_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_ppsqm_rent_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_sale_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_ly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_sale_ly", models.PositiveIntegerField(blank=True, null=True)),
                ("count_rent_ly", models.PositiveIntegerField(blank=True, null=True)),
                ("tx_per_unit_pm_ly", models.FloatField(blank=True, null=True)),
                ("roi_ly", models.FloatField(blank=True, null=True)),
                (
                    "avg_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("avg_sqm_sale_py", models.FloatField(blank=True, null=True)),
                ("avg_sqm_rent_py", models.FloatField(blank=True, null=True)),
                (
                    "avg_ppsqm_sale_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_ppsqm_rent_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "median_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_sale_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_rent_price_py",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("count_sale_py", models.PositiveIntegerField(blank=True, null=True)),
                ("count_rent_py", models.PositiveIntegerField(blank=True, null=True)),
                ("tx_per_unit_pm_py", models.FloatField(blank=True, null=True)),
                ("roi_py", models.FloatField(blank=True, null=True)),
                ("last_3_sales", models.JSONField(blank=True, null=True)),
                ("last_3_rents", models.JSONField(blank=True, null=True)),
                ("tx_per_unit_pm_ly_rent", models.FloatField(blank=True, null=True)),
                ("tx_per_unit_pm_py_rent", models.FloatField(blank=True, null=True)),
                ("avg_exposure_sale_days", models.FloatField(blank=True, null=True)),
                ("avg_exposure_rent_days", models.FloatField(blank=True, null=True)),
                ("avg_sale_per_unit_ratio", models.FloatField(blank=True, null=True)),
                (
                    "dld_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="main.building",
                    ),
                ),
            ],
            options={
                "unique_together": {("dld_building", "bedrooms")},
            },
        ),
    ]
