# Generated by Django 5.1.7 on 2025-04-15 08:29
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "numeric_area",
                    models.FloatField(
                        blank=True,
                        help_text="Некое числовое значение площади района, при желании.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PFJsonUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_file", models.FileField(upload_to="pfjson")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="pfimport.area",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "area")},
            },
        ),
        migrations.CreateModel(
            name="PFListRent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "display_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bedrooms", models.CharField(blank=True, max_length=10, null=True)),
                ("bathrooms", models.CharField(blank=True, max_length=10, null=True)),
                ("added_on", models.DateTimeField(blank=True, null=True)),
                ("broker", models.CharField(blank=True, max_length=100, null=True)),
                ("agent", models.CharField(blank=True, max_length=100, null=True)),
                ("agent_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "broker_license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "price_duration",
                    models.CharField(
                        blank=True,
                        help_text="sell / rent (из JSON priceDuration)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        blank=True,
                        help_text="Напр. 'Residential for Sale' (из JSON['type'])",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rera", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "size_min",
                    models.CharField(
                        blank=True,
                        help_text="Напр. '1961 sqft'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "numeric_area",
                    models.FloatField(
                        blank=True, help_text="Чисто число, напр. 1961", null=True
                    ),
                ),
                ("furnishing", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_html", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfimport.area",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfimport.building",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PFListSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "display_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bedrooms", models.CharField(blank=True, max_length=10, null=True)),
                ("bathrooms", models.CharField(blank=True, max_length=10, null=True)),
                ("added_on", models.DateTimeField(blank=True, null=True)),
                ("broker", models.CharField(blank=True, max_length=100, null=True)),
                ("agent", models.CharField(blank=True, max_length=100, null=True)),
                ("agent_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "broker_license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "price_duration",
                    models.CharField(
                        blank=True,
                        help_text="sell / rent (из JSON priceDuration)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        blank=True,
                        help_text="Напр. 'Residential for Sale' (из JSON['type'])",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rera", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "size_min",
                    models.CharField(
                        blank=True,
                        help_text="Напр. '1961 sqft'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "numeric_area",
                    models.FloatField(
                        blank=True, help_text="Чисто число, напр. 1961", null=True
                    ),
                ),
                ("furnishing", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_html", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfimport.area",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfimport.building",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
