# Generated by Django 5.1.7 on 2025-04-17 21:53
from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0002_area_numbers_of_main_page_ads_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="sum_sale_price",
            new_name="rent_count_1br",
        ),
        migrations.RemoveField(
            model_name="pflistrent",
            name="rera",
        ),
        migrations.RemoveField(
            model_name="pflistsale",
            name="rera",
        ),
        migrations.AddField(
            model_name="building",
            name="rent_count_2br",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_count_3br",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_count_4br",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_count_studio",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_sum_1br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_sum_2br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_sum_3br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_sum_4br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="rent_sum_studio",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_count_1br",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_count_2br",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_count_3br",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_count_4br",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_count_studio",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_sum_1br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_sum_2br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_sum_3br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_sum_4br",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="sale_sum_studio",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="sum_exposure_rent_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="sum_exposure_sale_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="area",
            name="numeric_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="verified_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="verified_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pfjsonupload",
            name="wipe_rent_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pfjsonupload",
            name="wipe_sale_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pflistrent",
            name="listing_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pflistrent",
            name="numeric_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pflistrent",
            name="price_duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="pflistrent",
            name="size_min",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pflistsale",
            name="listing_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pflistsale",
            name="numeric_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pflistsale",
            name="price_duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="pflistsale",
            name="size_min",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
