# Generated by Django 5.1.7 on 2025-04-17 22:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0003_rename_sum_sale_price_building_rent_count_1br_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pfjsonupload",
            name="wipe_area_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pfjsonupload",
            name="wipe_buildnig_before",
            field=models.BooleanField(default=False),
        ),
    ]
