# Generated by Django 5.1.7 on 2025-03-18 12:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_mergedtransaction_building_rooms_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="building_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of buildings in the project", null=True
            ),
        ),
        migrations.AlterField(
            model_name="buildingliquidityparameterone",
            name="ликвидность_параметр_one",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of sales in this month"
            ),
        ),
        migrations.AlterField(
            model_name="mergedtransaction",
            name="building_rooms_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="mergedtransaction",
            name="same_rooms_count_in_building",
            field=models.PositiveIntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name="mergedtransaction",
            name="sqm",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="Area in sq.ft. (if missing, set 0)",
                null=True,
            ),
        ),
    ]
