# Generated by Django 5.1.7 on 2025-03-18 13:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_searchtransactionslog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchtransactionslog",
            old_name="roperty_components",
            new_name="property_components",
        ),
    ]
