# Generated by Django 5.1.7 on 2025-03-18 18:50
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0006_rename_roperty_components_searchtransactionslog_property_components",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildingliquidityparameterone",
            old_name="ликвидность_параметр_one",
            new_name="liquidity_parameter_one",
        ),
    ]
