# Generated by Django 5.1.7 on 2025-03-18 20:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0007_rename_ликвидность_параметр_one_buildingliquidityparameterone_liquidity_parameter_one",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projects_file",
                    models.CharField(
                        default="projects_buildings_matched_fuzzy.xlsx",
                        help_text="Path to Excel file for projects and buildings",
                        max_length=255,
                    ),
                ),
                (
                    "transactions_file",
                    models.CharField(
                        default="filtered_20250315.csv",
                        help_text="Path to CSV file for transactions",
                        max_length=255,
                    ),
                ),
                (
                    "clean_data",
                    models.BooleanField(
                        default=False, help_text="Clean all objects before populating"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("on_going", "On Going"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
