# Generated by Django 5.1.7 on 2025-03-20 08:28
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_dataimport_projects_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="year",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="Mounth",
        ),
        migrations.DeleteModel(
            name="Year",
        ),
    ]
