# Generated by Django 5.1.7 on 2025-04-03 16:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_mergedrentaltransaction"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mergedrentaltransaction",
            name="main_merged_meter_s_9a7ec2_idx",
        ),
        migrations.RenameField(
            model_name="mergedrentaltransaction",
            old_name="meter_sale_price",
            new_name="maybe_it_field_will_help",
        ),
        migrations.AddIndex(
            model_name="mergedrentaltransaction",
            index=models.Index(
                fields=["maybe_it_field_will_help", "deal_year"],
                name="main_merged_maybe_i_d04339_idx",
            ),
        ),
    ]
