# Generated by Django 5.1.7 on 2025-04-03 16:16
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0014_remove_mergedrentaltransaction_main_merged_meter_s_9a7ec2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.project",
            ),
        ),
    ]
