# Generated by Django 5.1.7 on 2025-04-06 07:08
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0016_remove_mergedrentaltransaction_main_merged_transac_e69b47_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
