# Generated by Django 5.1.7 on 2025-04-06 07:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_mergedrentaltransaction_contract_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="meter_sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
