# Generated by Django 5.1.7 on 2025-05-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0019_mergedrentaltransaction_meter_sale_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_rooms", models.CharField(db_index=True, max_length=50)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("prev_period_start", models.DateField()),
                ("prev_period_end", models.DateField()),
                (
                    "avg_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_sales", models.PositiveIntegerField()),
                ("rooms_count_sales", models.PositiveIntegerField()),
                ("liquidity_sales", models.FloatField()),
                (
                    "avg_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_sales_prev", models.PositiveIntegerField()),
                ("rooms_count_sales_prev", models.PositiveIntegerField()),
                ("liquidity_sales_prev", models.FloatField()),
                (
                    "avg_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_rental", models.PositiveIntegerField()),
                ("rooms_count_rental", models.PositiveIntegerField()),
                ("liquidity_rental", models.FloatField()),
                (
                    "avg_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_rental_prev", models.PositiveIntegerField()),
                ("rooms_count_rental_prev", models.PositiveIntegerField()),
                ("liquidity_rental_prev", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_snapshots",
                        to="main.area",
                    ),
                ),
            ],
            options={
                "ordering": ("-period_start", "area", "number_of_rooms"),
                "unique_together": {
                    ("area", "number_of_rooms", "period_start", "period_end")
                },
            },
        ),
        migrations.CreateModel(
            name="BuildingReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_rooms", models.CharField(db_index=True, max_length=50)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("prev_period_start", models.DateField()),
                ("prev_period_end", models.DateField()),
                (
                    "avg_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_sales",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_sales", models.PositiveIntegerField()),
                ("total_units", models.PositiveIntegerField()),
                ("rooms_count_sales", models.PositiveIntegerField()),
                ("liquidity_sales", models.FloatField()),
                (
                    "avg_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_sales_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_sales_prev", models.PositiveIntegerField()),
                ("rooms_count_sales_prev", models.PositiveIntegerField()),
                ("liquidity_sales_prev", models.FloatField()),
                (
                    "avg_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_rental",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_rental", models.PositiveIntegerField()),
                ("rooms_count_rental", models.PositiveIntegerField()),
                ("liquidity_rental", models.FloatField()),
                (
                    "avg_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "median_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "min_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "max_price_rental_prev",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transactions_count_rental_prev", models.PositiveIntegerField()),
                ("rooms_count_rental_prev", models.PositiveIntegerField()),
                ("liquidity_rental_prev", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_snapshots",
                        to="main.building",
                    ),
                ),
            ],
            options={
                "ordering": ("-period_start", "building", "number_of_rooms"),
                "unique_together": {
                    ("building", "number_of_rooms", "period_start", "period_end")
                },
            },
        ),
    ]
