# Generated by Django 5.1.7 on 2025-05-02 22:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "building_reports",
            "0003_rename_rooms_count_buildingreportsnapshot_rooms_count_sales_and_more",
        ),
        ("pfimport", "0006_building_dld_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="PFSnapshotBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        db_index=True,
                        help_text="Нормализованная комнатность: studio, 1br, 2br, 3br или 4br",
                        max_length=10,
                    ),
                ),
                (
                    "avg_sale_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "avg_rent_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "median_sale_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "median_rent_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "min_sale_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "max_sale_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "min_rent_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "max_rent_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("avg_exposure_sale", models.FloatField(default=0)),
                ("avg_exposure_rent", models.FloatField(default=0)),
                ("sale_count", models.PositiveIntegerField(default=0)),
                ("rent_count", models.PositiveIntegerField(default=0)),
                (
                    "ads_per_unit_sale",
                    models.FloatField(default=0, help_text="sale_count / total_units"),
                ),
                (
                    "ads_per_unit_rent",
                    models.FloatField(default=0, help_text="rent_count / total_units"),
                ),
                (
                    "roi",
                    models.FloatField(
                        default=0, help_text="avg_rent_price / avg_sale_price"
                    ),
                ),
                (
                    "liquidity_sale",
                    models.FloatField(
                        default=0, help_text="sale_count / total_units / 12"
                    ),
                ),
                (
                    "liquidity_rent",
                    models.FloatField(
                        default=0, help_text="rent_count / total_units / 12"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_snapshots",
                        to="pfimport.building",
                    ),
                ),
            ],
            options={
                "ordering": ("building", "bedrooms"),
                "unique_together": {("building", "bedrooms")},
            },
        ),
    ]
