global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "memory-service"
    static_configs:
      - targets: ["memory-service-production:8080"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-production:5432"]
    metrics_path: "/metrics"
    scrape_interval: 30s
