# Generated by Django 5.1.7 on 2025-03-18 13:24
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_building_building_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTransactionsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "search_substring",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "roperty_components",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("period", models.CharField(blank=True, max_length=50, null=True)),
                ("avg_price", models.FloatField(blank=True, null=True)),
                (
                    "transaction_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "transaction_count_change_percent",
                    models.FloatField(blank=True, null=True),
                ),
                ("median_price", models.FloatField(blank=True, null=True)),
                (
                    "median_price_change_percent",
                    models.FloatField(blank=True, null=True),
                ),
                ("avg_price_per_sqft", models.FloatField(blank=True, null=True)),
                ("building_count", models.PositiveIntegerField(blank=True, null=True)),
                ("total_units", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "price_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("special_liquidity_calc", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
