# Generated by Django 5.1.7 on 2025-03-18 20:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_dataimport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimport",
            name="projects_file",
            field=models.FileField(
                help_text="file for projects and buildings", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="dataimport",
            name="transactions_file",
            field=models.FileField(help_text="CSV file for transactions", upload_to=""),
        ),
    ]
