# Generated by Django 5.1.7 on 2025-03-23 22:29
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_dataimport_projects_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="main.building",
            ),
        ),
    ]
