# Generated by Django 5.1.7 on 2025-04-03 12:13
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_room_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergedRentalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        db_index=True, default="rental", editable=False, max_length=10
                    ),
                ),
                (
                    "date_of_transaction",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "building_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "number_of_rooms",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("sqm", models.FloatField(blank=True, db_index=True, null=True)),
                (
                    "transaction_price",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("detail_link", models.URLField(blank=True, db_index=True, null=True)),
                (
                    "period",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "meter_sale_price",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "deal_year",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.area",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.building",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["transaction_price", "sqm"],
                        name="main_merged_transac_e69b47_idx",
                    ),
                    models.Index(
                        fields=["meter_sale_price", "deal_year"],
                        name="main_merged_meter_s_9a7ec2_idx",
                    ),
                    models.Index(
                        fields=["period"], name="main_merged_period_9f6428_idx"
                    ),
                ],
            },
        ),
    ]
