# Generated by Django 5.1.7 on 2025-04-06 06:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_mergedrentaltransaction_project"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mergedrentaltransaction",
            name="main_merged_transac_e69b47_idx",
        ),
        migrations.RemoveIndex(
            model_name="mergedrentaltransaction",
            name="main_merged_maybe_i_d04339_idx",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="building_name",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="deal_year",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="detail_link",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="location_name",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="maybe_it_field_will_help",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="number_of_rooms",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="sqm",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="transaction_price",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="verified_at",
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="actual_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="annual_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="area_id_csv",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="area_name_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="area_name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="contract_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="contract_id",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="contract_reg_type_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="contract_reg_type_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="contract_reg_type_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_bus_property_type_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_bus_property_type_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_bus_property_type_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_property_sub_type_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_property_sub_type_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_property_sub_type_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_property_type_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_property_type_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="ejari_property_type_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="is_free_hold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="master_project_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="master_project_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="nearest_landmark_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="nearest_landmark_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="nearest_mall_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="nearest_mall_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="nearest_metro_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="nearest_metro_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="no_of_prop",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="project_name_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="project_name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="project_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="property_usage_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="property_usage_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="tenant_type_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="tenant_type_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="tenant_type_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
