# Generated by Django 5.1.7 on 2025-04-06 07:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_mergedrentaltransaction_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mergedrentaltransaction",
            name="contract_amount",
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="building_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="detail_link",
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="location_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="number_of_rooms",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="something_important_v1",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="sqm",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="Area in sq.ft. (if missing, set 0)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mergedrentaltransaction",
            name="transaction_price",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
