---
- hosts: all
  become: true
  vars:
    nginx_path: /etc/nginx
    nginx_sites: "{{ nginx_path }}/sites-enabled"
    my_hostname: dev.propertix.ai
    name_project: realty
    work_dir: "/home/panchuk35/{{ name_project }}"
    app_port: 8000
    acme_email: "info@{{ my_hostname }}"

  tasks:

    - name: Add task for letsencrypt
      ansible.builtin.command: "sudo certbot certonly -n -d {{ my_hostname }} --agree-tos --email {{ acme_email }} --webroot --webroot-path /usr/share/nginx/html"

    - name: Add cron task for letsencrypt cert update
      cron:
        name: "Cron for certbot cert update"
        minute: "5"
        hour: "1"
        day: "5,10,15,20,25"
        user: "root"
        job: "certbot certonly -n -d {{ my_hostname }} --agree-tos --email {{ acme_email }} --webroot --webroot-path /usr/share/nginx/html && /etc/init.d/nginx restart"
      tags: ["install", "cron"]

    - name: Setup nginx vhost
      template:
        src=yoursite.com-ssl.conf.tpl
        dest="{{ nginx_sites }}/{{ my_hostname }}.conf"
      notify: restart nginx

    - name: "Allow all access to tcp port 443"
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp

  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted
