---
- hosts: all
  become: true

  vars:
    name_project: realty
    work_dir: "/home/panchuk35/{{ name_project }}"

  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - ufw
          - nginx
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3
          - python3-pip
          - virtualenv
          - python3-setuptools
          - rsync
          - sshpass
          - cron
          - certbot
        state: latest
        update_cache: true

    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny

    - name: Add work dir
      ansible.builtin.file:
        path: "{{ work_dir }}/public"
        state: directory

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Get gitlab-runner
      ansible.builtin.get_url:
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
        dest: /home/panchuk35/script.deb.sh
        mode: '0440'

    - name: Set gitlab-runner
      ansible.builtin.command: bash /home/panchuk35/script.deb.sh

    - name: Rm gitlab-runner sh
      ansible.builtin.command: rm /home/panchuk35/script.deb.sh

    - name: Install gitlab-runner
      apt:
        pkg:
          - gitlab-runner
        state: latest
        update_cache: true

    - name: Add gitlab-runner in sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'gitlab-runner ALL=(ALL) NOPASSWD: ALL'
