# Generated by Django 5.1.7 on 2025-03-18 12:16
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_building_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedtransaction",
            name="building_rooms_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Если у проекта только 1 здание, то равно Project.total_units, иначе 0",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mergedtransaction",
            name="same_rooms_count_in_building",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Сколько квартир в этом здании имеют такое же количество комнат, что и у данной транзакции",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Сколько всего зданий (building) у этого проекта (включая текущее).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mergedtransaction",
            name="sqm",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="Площадь в квадратных футах (sq.ft.)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BuildingLiquidityParameterOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "ликвидность_параметр_one",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Сколько покупок (Sales) в данном месяце для этого здания",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidity_stats",
                        to="main.building",
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "year", "month")},
            },
        ),
    ]
