# Generated by Django 5.1.7 on 2025-03-23 18:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_year_transaction_delete_mounth_delete_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataimport",
            name="projects_file",
        ),
        migrations.RemoveField(
            model_name="dataimport",
            name="transactions_file",
        ),
        migrations.AddField(
            model_name="dataimport",
            name="projects_zipfile",
            field=models.FileField(
                blank=True, help_text="Project zip file", upload_to=""
            ),
        ),
    ]
