# Generated by Django 5.1.7 on 2025-05-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_mergedrentaltransaction_meter_sale_price"),
        ("pfimport", "0006_building_dld_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "english_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "arabic_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="building",
            name="area_by_pf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pfimport.area",
            ),
        ),
        migrations.AddField(
            model_name="mergedtransaction",
            name="master_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_transactions",
                to="main.masterproject",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="master_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="main.masterproject",
            ),
        ),
    ]
