# Generated by Django 5.1.7 on 2025-05-21 15:53

import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_masterproject_building_area_by_pf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "giper_csv_url",
                    models.URLField(verbose_name="URL giper_matched_output.csv"),
                ),
                (
                    "transactions_csv_url",
                    models.URLField(verbose_name="URL tr_*.csv (большой)"),
                ),
                ("chunk_size", models.PositiveIntegerField(default=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=12,
                    ),
                ),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
