# Generated by Django 5.1.7 on 2025-04-16 22:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="numbers_of_main_page_ads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="area",
            name="numbers_of_processed_ads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="area",
            name="sum_number_of_days_for_all_ads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="area",
            name="verified_value",
            field=models.CharField(
                blank=True,
                help_text="Напр. 'Jumeirah Village Circle (7,431)'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="numbers_of_processed_ads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="sum_sale_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="verified_value",
            field=models.CharField(
                blank=True,
                help_text="Напр. 'Sterling West House'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pfjsonupload",
            name="wipe_rent_before",
            field=models.BooleanField(
                default=False, verbose_name="Очистить PFListRent перед импортом"
            ),
        ),
        migrations.AddField(
            model_name="pfjsonupload",
            name="wipe_sale_before",
            field=models.BooleanField(
                default=False, verbose_name="Очистить PFListSale перед импортом"
            ),
        ),
    ]
