# Generated by Django 5.1.7 on 2025-04-17 23:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0004_pfjsonupload_wipe_area_before_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="numbers_of_processed_ads",
            new_name="numbers_of_processed_rent_ads",
        ),
        migrations.AddField(
            model_name="building",
            name="numbers_of_processed_sale_ads",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
