# Generated by Django 5.1.7 on 2025-04-22 23:04
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_mergedrentaltransaction_meter_sale_price"),
        (
            "pfimport",
            "0005_rename_numbers_of_processed_ads_building_numbers_of_processed_rent_ads_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="dld_building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.building",
            ),
        ),
    ]
