# Generated by Django 5.1.7 on 2025-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0006_building_dld_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="created_by",
            field=models.CharField(
                choices=[
                    ("user", "Created manually / through admin"),
                    ("geojson_import", "Imported from geojson script"),
                ],
                db_index=True,
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="geometry_json",
            field=models.JSONField(
                blank=True,
                help_text="Полный GeoJSON geometry мультиполигона",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
