# Generated by Django 5.1.7 on 2025-05-21 19:02

import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pfimport",
            "0007_area_created_by_area_geometry_json_building_latitude_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PFJsonImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_url", models.URLField(verbose_name="URL JSON-файла")),
                ("wipe_sale_before", models.BooleanField(default=False)),
                ("wipe_rent_before", models.BooleanField(default=False)),
                ("wipe_area_before", models.BooleanField(default=False)),
                ("wipe_buildnig_before", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=12,
                    ),
                ),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
