# Generated by Django 5.1.7 on 2025-05-21 20:13

import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0008_pfjsonimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text='Не пишите "python manage.py" – только саму команду и её аргументы.',
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
