# Generated by Django 5.1.7 on 2025-05-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0009_commandjob"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pflistrent",
            index=models.Index(
                fields=["area", "verified"], name="pfimport_pf_area_id_301fe3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistrent",
            index=models.Index(
                fields=["building"], name="pfimport_pf_buildin_3b316e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistrent",
            index=models.Index(fields=["price"], name="pfimport_pf_price_2a8de4_idx"),
        ),
        migrations.AddIndex(
            model_name="pflistrent",
            index=models.Index(
                fields=["numeric_area"], name="pfimport_pf_numeric_e8936a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistrent",
            index=models.Index(
                fields=["added_on"], name="pfimport_pf_added_o_c36102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistrent",
            index=models.Index(
                fields=["bedrooms", "price"], name="pfimport_pf_bedroom_5f45da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistsale",
            index=models.Index(
                fields=["area", "verified"], name="pfimport_pf_area_id_9ac25d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistsale",
            index=models.Index(
                fields=["building"], name="pfimport_pf_buildin_196f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistsale",
            index=models.Index(fields=["price"], name="pfimport_pf_price_6970ac_idx"),
        ),
        migrations.AddIndex(
            model_name="pflistsale",
            index=models.Index(
                fields=["numeric_area"], name="pfimport_pf_numeric_c5693a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistsale",
            index=models.Index(
                fields=["added_on"], name="pfimport_pf_added_o_05d8b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pflistsale",
            index=models.Index(
                fields=["bedrooms", "price"], name="pfimport_pf_bedroom_414e6e_idx"
            ),
        ),
    ]
