# Generated by Django 5.1.7 on 2025-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfimport", "0010_pflistrent_pfimport_pf_area_id_301fe3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pflistrent",
            name="building_avg_roi",
            field=models.FloatField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Среднее ROI по зданию",
            ),
        ),
        migrations.AddField(
            model_name="pflistrent",
            name="roi",
            field=models.FloatField(
                blank=True, db_index=True, null=True, verbose_name="ROI объявления"
            ),
        ),
        migrations.AddField(
            model_name="pflistsale",
            name="building_avg_roi",
            field=models.FloatField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Среднее ROI по зданию",
            ),
        ),
        migrations.AddField(
            model_name="pflistsale",
            name="roi",
            field=models.FloatField(
                blank=True, db_index=True, null=True, verbose_name="ROI объявления"
            ),
        ),
    ]
