name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'realty-main/**'
      - 'pfimport-main/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'realty-main/**'
      - 'pfimport-main/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies for realty-main
        run: pip install -r realty-main/requirements.txt

      - name: Run tests for realty-main
        working-directory: ./realty-main
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/test_db
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: "True"
        run: python manage.py test

      # Добавьте шаги для pfimport-main, если у него есть свои тесты
      # - name: Install dependencies for pfimport-main
      #   run: pip install -r pfimport-main/requirements.txt
      # 
      # - name: Run tests for pfimport-main
      #   working-directory: ./pfimport-main
      #   run: pytest
